services:
  mongo:
    image: mongo:7
    container_name: vinted-mongo
    ports:
      - "27017:27017"
    restart: unless-stopped

  backend:
    image: mcr.microsoft.com/playwright:v1.57.0-jammy
    container_name: vinted-backend
    working_dir: /app
    volumes:
      - ./backend:/app
    command: sh -c "npm install && node server.js"
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    restart: unless-stopped
